Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,6 +26,11 @@ jobs:
       - name: Get Tags
         run: |
           tag=${{ github.event.ref }}
+          if ! [[ tag ~= refs/tag ]]; then
+            echo "error: no version tag"
+            exit 1
+          fi
+          
           THIS_TAG=${tag##*/}
           echo "THIS_TAG=${THIS_TAG}" >> "$GITHUB_ENV"
           echo "${THIS_TAG}"
