2024042203

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,12 +28,14 @@ jobs:
       - name: Get Tags
         run: |
           refTag=${{ github.event.ref }}
-          echo "THIS_TAG=${regTag##*/}" >> "$GITHUB_ENV"
+          THIS_TAG=${regTag##*/}
           echo "${THIS_TAG}"
-          if [ -z "${THIS_TAG}" ]; then
-            echo "error: invalid tags"
-            exit 1
-          fi 
+        # echo "THIS_TAG=${regTag##*/}" >> "$GITHUB_ENV"
+        # echo "${THIS_TAG}"
+        # if [ -z "${THIS_TAG}" ]; then
+        #   echo "error: invalid tags"
+        #   exit 1
+        # fi 
       # - name: Checkout repository
       #   uses: actions/checkout@v4      
 
